version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql  # Nombre del servicio de MySQL, no una IP
      DB_USER: usuario
      DB_PASSWORD: contraseña
      DB_NAME: noteblog
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: noteblog
      MYSQL_USER: usuario
      MYSQL_PASSWORD: contraseña
    ports:
      - "3306:3306"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
